# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_continuous_points_above_thr <- function(v, i_start, num, thr, n_skip) {
    .Call('_Met4DX_check_continuous_points_above_thr', PACKAGE = 'Met4DX', v, i_start, num, thr, n_skip)
}

get_continuous_points_above_thr_idx <- function(v, i_start, num, thr, n_skip) {
    .Call('_Met4DX_get_continuous_points_above_thr_idx', PACKAGE = 'Met4DX', v, i_start, num, thr, n_skip)
}

find_greater_equal_than <- function(data, values) {
    .Call('_Met4DX_find_greater_equal_than', PACKAGE = 'Met4DX', data, values)
}

find_dense_min <- function(values, i_max) {
    .Call('_Met4DX_find_dense_min', PACKAGE = 'Met4DX', values, i_max)
}

rect_unique <- function(data, order, diff) {
    .Call('_Met4DX_rect_unique', PACKAGE = 'Met4DX', data, order, diff)
}

